### PR TITLE
Fix issue with arch linux client

### PR DESCRIPTION
**Pull request by samyak-jain**
Fixes Issue #24

### CODE REVIEW

**Comment by zimhat** [comment]
I am using your fix with success so thank you very much. But have you been able to sync medias using anki 2.1.26 ? That's issue #58

**Comment by samyak-jain** [comment]
@zimhat Haven't gotten a chance to try with 2.1.26. But 2.1.35-3 is working for me after this fix. Since you are using arch, I wonder why you are using such an old version?

**Comment by zimhat** [comment]
One of my addons wasn't directly compatible with anki 2.1.35 but now it's fixed. I still get an error while syncing medias though, see #59

**Comment by VikashKothary** [comment]
So this PR looked good to me. @zimhat we'll try and get your issue solved but I don't consider this a blocker.

Thanks so much for your contribution @samyak-jain!

**Pull request merged**
