### PR TITLE
fix:'NoneType' object is not subscriptable_41_

### PR DESCRIPTION
**Pull request by dobefore**
this PR may be inconsistent with previous version.
@wsgify
    def __call__(self, req):
        data = req.POST['data'].file.read()
         data = self._decode_data(data, compression)

return value of grave in data is None
so coerce it to default value

### CODE REVIEW

**Comment by VikashKothary** [comment]
Hi @dobefore, thanks for another great fix. 

I just want to understand what you mean by "may be inconsistent with previous version".
Is this going to be a breaking changes for older versions of Anki Desktop?

**Comment by dobefore** [comment]
> I just want to understand what you mean by "may be inconsistent with previous version".
> Is this going to be a breaking changes for older versions of Anki Desktop?

Yes,you're right! please see issue #93

**Comment by dobefore** [comment]
@VikashKothary ,I'm Sorry not think about earlier support.
I've tested It's been working on 2.1.40,so it may work too before 2.1.40.
So I might say thing goes well before and after 2.1.40.
Would like you to approve it!

**Comment by VikashKothary** [comment]
Let's merge it since it does seem to be a fix. But if there are backward compatibility issues then we can deal with it then.

Thanks you for your contribution.

**Pull request merged**
