### PR TITLE
add Dockerimage

### LINKED ISSUE #149: Docker Releases
As the docker container build in the [anki-devops-service](https://github.com/ankicommunity/anki-devops-services) is out of date. Last release 2 years ago with version 2.1.0 to someones private dockerhub account. 

I would suggest to use the included docker registry of github, which is for free for opensource projects and doesn't have the download limitations" of dockerhub.
Furthermore the control over the registry will be within the repository.

I would also argue that the docker container should be build within the project itself.

We could also provide a develop version as container.

I can provide a PR with the implementation.

### PR DESCRIPTION
**Pull request by LuckyTurtleDev**
* add Dockerfile
* build and publish image with github ci

Releases will be tagged with `lasted`, other commits will be tagged witch the branch name.

If this pr is wanted, I can add a readme with example configuration, including a docker-compose.

A image for testing is available at  `ghcr.io/luckyturtledev/anki-sync-server:docker` .
Example docker-compose:
```yml
version: '3.3'
services:
    anki:
        image: ghcr.io/luckyturtledev/anki-sync-server:docker
        container_name: anki
        ports:
         - 127.0.0.1:27701:27701
        volumes:
            - './data:/data'
        user: 1000:1000
        restart: unless-stopped
```
The (empty) folder `data`  owned by 1000:1000 should exist before the container start.
Alternative the `user: 1000:1000` line can be removed.

This fix https://github.com/ankicommunity/anki-sync-server/issues/149

### CODE REVIEW

**Comment by JuliusFreudenberger** [comment]
I tried to build this image with the Dockerfile you provide.
However, with the release of python 3.11 in october, this image no longer builds. I had to downgrade the base image to `python:3.10-slim`.
The error (it is regarding no rust compiler found in the base image, which is to be expected) can be found below:

```
 > [3/7] RUN cd /src && pip install -r requirements.txt && pip install -e .:                                                                                   
#0 2.059 Collecting anki==2.1.49                                                                                                                               
#0 2.120   Downloading anki-2.1.49-cp38-abi3-manylinux2014_x86_64.whl (9.9 MB)                                                                                 
#0 16.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 678.0 kB/s eta 0:00:00                                                                       
#0 16.78 Collecting beautifulsoup4==4.11.1                                                                                                                     
#0 16.79   Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
#0 17.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 470.9 kB/s eta 0:00:00
#0 17.13 Collecting certifi==2022.6.15
#0 17.18   Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
#0 17.43      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 907.3 kB/s eta 0:00:00
#0 17.56 Collecting charset-normalizer==2.1.0
#0 17.61   Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
#0 17.83 Collecting decorator==4.4.2
#0 17.88   Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
#0 17.98 Collecting distro==1.7.0
#0 17.99   Downloading distro-1.7.0-py3-none-any.whl (20 kB)
#0 18.14 Collecting idna==3.3
#0 18.17   Downloading idna-3.3-py3-none-any.whl (61 kB)
#0 18.29      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 682.6 kB/s eta 0:00:00
#0 18.43 Collecting importlib-metadata==4.12.0
#0 18.46   Downloading importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
#0 18.70 Collecting markdown==3.3.7
#0 18.80   Downloading Markdown-3.3.7-py3-none-any.whl (97 kB)
#0 19.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 144.0 kB/s eta 0:00:00
#0 20.10 Collecting orjson==3.7.5
#0 20.15   Downloading orjson-3.7.5.tar.gz (640 kB)
#0 22.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 640.2/640.2 kB 270.9 kB/s eta 0:00:00
#0 22.76   Installing build dependencies: started
#0 60.99   Installing build dependencies: finished with status 'done'
#0 61.00   Getting requirements to build wheel: started
#0 61.04   Getting requirements to build wheel: finished with status 'done'
#0 61.04   Preparing metadata (pyproject.toml): started
#0 61.08   Preparing metadata (pyproject.toml): finished with status 'error'
#0 61.08   error: subprocess-exited-with-error
#0 61.08   
#0 61.08   × Preparing metadata (pyproject.toml) did not run successfully.
#0 61.08   │ exit code: 1
#0 61.08   ╰─> [6 lines of output]
#0 61.08       
#0 61.08       Cargo, the Rust package manager, is not installed or is not on PATH.
#0 61.08       This package requires Rust and Cargo to compile extensions. Install it through
#0 61.08       the system's package manager or via https://rustup.rs/
#0 61.08       
#0 61.08       Checking for Rust toolchain....
#0 61.08       [end of output]
#0 61.08   
#0 61.08   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 61.08 error: metadata-generation-failed
#0 61.08 
#0 61.08 × Encountered error while generating package metadata.
#0 61.08 ╰─> See above for output.
#0 61.08 
#0 61.08 note: This is an issue with the package mentioned above, not pip.
#0 61.08 hint: See above for details.
------
failed to solve: process "/bin/sh -c cd /src && pip install -r requirements.txt && pip install -e ." did not complete successfully: exit code: 1
```

**Comment by LuckyTurtleDev** [comment]
@JuliusFreudenberger

> The error (it is regarding no rust compiler found in the base image, which is to be expected) can be found below:

Yes their is no rust compiler available. With version of anki-sync have you tried?
Their is an new release since I have create the Dockerfile.
However installing rustup and downloading the latest stable toolchain should be an easy fix.

 Python 3.11 is not a major release so their should be no breaking change. However using the old version should be an option.


I will update the Dockerfile later.

**Comment by LuckyTurtleDev** [comment]
I have merge the develop branch and update the base image. It does build fine without any issues with python 3.10.

**Comment by JuliusFreudenberger** [comment]
I built the image against the latest release tag [v2.4.0](https://github.com/ankicommunity/anki-sync-server/releases/tag/v2.4.0). I did not try out the latest develop.

I do not have that much experience with the rust toolchain, but installing the compiler should in theory solve the issue as well.
I just wondered that the build was successful on my host and not in the docker build process. Only difference was the python version (3.10 local vs. 3.11 docker), as I do not have a rust compiler on my host.

Thank you for the Dockerfile in the first place, the container is running smoothly since.

**Comment by bee-san** [comment]
Can we merge this? :)

**Comment by VikashKothary** [comment]
Yep. I don't see why not :)

**Comment by woj-tek** [comment]
Shouldn't it be pushed to the main repo instead of `LuckyTurtleDev`? I.e. currently it's available in https://github.com/luckyturtledev/anki-sync-server/pkgs/container/anki-sync-server and https://github.com/orgs/ankicommunity/packages?repo_name=anki-sync-server (https://github.com/orgs/ankicommunity/pkgs/container/anki-sync-server) is empty. I don't see anything explicitly specifying repo name. 

I check the build (https://github.com/ankicommunity/anki-sync-server/actions/runs/5556067171/jobs/10148093474#step:7:343) and it specifies `"image.name": "ghcr.io/ankicommunity/anki-sync-server:develop"` as image, but trying to use gives 404.

**Comment by VikashKothary** [comment]
Ah yes, I didn't review the MR properly. You are correct, we need to update the GitHub Actions to deploy to our DockerHub account. I've created an issue here: https://github.com/ankicommunity/anki-sync-server/issues/163

**Pull request merged**
